### ISSUE TITLE
Playtesting Binary Search... Not very friendly

### ISSUE THREAD

**Issue by Byroni** [Bananapen/Research-Project#28]
Binary search is a little... odd to play through. The biggest issue is that there is no comparison values. If the player searches the middle first, than they have no idea whether to search left side or right side, because there is nothing to compare them to. We need to add numbers or letters so the player knows how to compare them.

Secondly, the rooms are very large and hard to see. For the player to know which one to open first, they have to step back and literally count the number of rooms. It feels hard to navigate and awkward to do. 

Lastly, this really applies to all games (scenes), we need to give the player direction and some kind of guidance. (I understand this is coming later on, but just something to keep note of)

**Comment by LupenWonse** [comment]
Absolutely right. Let's write specific issues for all the improvement ideas so that it will be easier to implement

**Comment by LupenWonse** [comment]
I think with the new fixes there were some improvements.
